- name: variable in ansible
  hosts: mongodb
  vars:
   COURSE: Devops
   TRAINER: Python life
   DURATION: 100hrs
  tasks:  ## using variable in playbook, to print massages ##
  - name: print hello world
    ansible.builtin.debug:
     msg: "i am learning devops"
  - name: print in variables
    ansible.builtin.debug:
     msg: "hello, i am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"


