- name: variables from prompt
  hosts: localhost
  var_prompt:
  - name: USERNAME # USERNAME means what variable you want to pass here that variable stories here # 
    prompt: please enter your username # prompt means its asks the what we want to pass username #
    private: false # false means (shows the text) # true means (not shows the text)
  - name: PASSWORD
    prompt: please enter your password
    private: true
  tasks:
  - name: printing variables
    ansible.builtin.debug:
     msg: "username is {{USERNAME}}, password is {{PASSWORD}}"