- name: variables at task level
  hosts: localhost
  vars:
  - money: "100rs"
    land: "100hectars"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
    msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add values
    vars:
    - money: "200"
      houses: "3 houses"
    ansible.builtin.debug:
     msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"
        