- name: variables form inventory
  hosts: mongodb
  tasks: # this is variables we written in inventory filr #
  - name: print mongodb username                   # [mongodb] #
    ansible.builtin.debug:                         # MONGO_USERNAME=mongodb # 
     msg: "username is: {{MONGO_USERNAME}}"        # MONGO_DB=categories #


