- name: simple condition
  hosts: localhost
  vars:
   NAME: DevOps
  tasks: ## this if name is devops then only this script will run ##
  - name: run this if name is DevOps
    ansible.builtin.debug:
     msg: "HELLO...{{NAME}}"
    when: NAME == "DevOps" ## here if names double equal to DevOps then its run ## 