- name: simple condition
  hosts: localhost
  vars:
   NAME: DEVOPS
  tasks: ## this if name is devops then only this script will run ##
  - name: run this if NAME is DEVOPS
    ansible.builtin.debug:
     msg: "HELLO...{{NAME}}"
    when: NAME == DEVOPS