- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
     name: "{{item}}" ## item means nginx stors in item ## 
     state: installed
    loop:
    - nginx
    - postfix