- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
     name: "{{item.name}}"
     state: "{{item.state}}"
    loop: ## installing and removeing packages using loop Topic ##
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'maven', state: 'absent'}
    - {name: 'mailx', state: 'installed'}