- name: Remove packages
  hosts: mongodb
  become: yes
  tasks:
  - name: Remove packages
    ansible.builtin.remove:
     name: "{{item}}" ## item means nginx stors in item ## 
     state: absent
    loop:
    - nginx
    - postfix
    - maven